# Generated by Django 5.2.7 on 2026-01-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_business_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_wallet',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='is_rewarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
