# Generated by Django 5.2.7 on 2026-03-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_wallet_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownercoinpurchaserequest',
            name='payment_proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
