# Generated by Django 5.2.7 on 2026-03-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_support_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bonus_coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='support_attachments/'),
        ),
    ]
