# Generated by Django 5.2.7 on 2026-03-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_set_exchange_rate_and_sadat_coins'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('cnic', models.CharField(max_length=15)),
                ('role', models.CharField(default='customer', max_length=20)),
                ('business_data', models.JSONField(blank=True, default=dict)),
                ('otp', models.CharField(max_length=6)),
                ('otp_expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
